on:
  push:
     branches:
       - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        python-version: ['3.7']
    steps:
      - name: Install Ubuntu packages
        if: matrix.os == 'ubuntu-latest' 
        run: sudo apt-get install -y software-properties-common libxml2-dev zlib1g-dev libcurl4-openssl-dev wget
    # python
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install Dependencies
        run: pip install -r requirements.txt
      # R
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      # Renv
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      # pandoc
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # The pandoc version to download (if necessary) and use.
      # tinytex
      - uses: r-lib/actions/setup-tinytex@v2
      # Run Snakemake
      - name: Run Snakemake
        run: snakemake all --cores 1